name: Graphviz documentation CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: environement
      run: sudo apt-get install -y graphviz
    - name: make
      run: make -f Makefile_doc
